name: add emoji to PR issue
on:
  pull_request:
    branch: [master]
    types: [opened, reopened]
jobs:
  add-emoji:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: npm install --save=false @actions/github
      # "+1"| "++1(-1)"| "laugh"| "confused"| "heart"| "hooray"| "rocket"| "eyes"
      - run: node .github/actions/createReaction.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
